#!/bin/bash

interactive_mode() {
    echo "Interactive mode - Enter images one by one:"
    img_search_exe="./img-search"
    image_to_compare="$1"
    database_path="$2"

    while read -r image; do
        if [ -f "$image" ]; then
            echo "$image_to_compare" | $img_search_exe "$image" "$database_path"
        else
            echo "Invalid image path: $image"
        fi
    done
}

automatic_mode() {
    echo "Automatic mode"
    img_search_exe="./img-search"
    image_to_compare="$1"
    database_path="${2:-./img/}"

    if [ -d "$database_path" ]; then
        # Use list-file script to get a list of images in the directory
        image_list=$(./list-file "$database_path")

        # Append the database_path to each image in the list
        image_list_with_path=""
        while read -r image; do
            if [ -f "$database_path$image" ]; then
                image_list_with_path="$image_list_with_path $database_path$image"
            else
                echo "Invalid image path: $database_path$image"
            fi
        done <<< "$image_list"

        # Pass both the image to compare and the list to img-search
        echo "$image_to_compare $image_list_with_path" | $img_search_exe
    else
        echo "Invalid database path: $database_path"
    fi
}

if [ "$1" == "-i" ] || [ "$1" == "--interactive" ]; then
    interactive_mode "$2" "$3"
elif [ "$1" == "-a" ] || [ "$1" == "--automatic" ]; then
    automatic_mode "$2" "$3"
else
    echo "Usage: $0 [-i|--interactive|-a|--automatic] image [database_path]"
    exit 1
fi

