#!/bin/bash

# Check if the directory path is provided as a command line argument
if [ $# -ne 1 ]; then
    echo "Missing directory name." >&2
    exit 1
fi

# Get the directory path from the command line argument
directory="$1"

# Check if the path is a directory
if [ ! -d "$directory" ]; then
    echo "The specified path is not a directory." >&2
    exit 2
fi

# List files in the directory (ignores subdirectories)
ls -p "$directory" | grep -v '/'


